apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
  namespace: playground
  labels:
    app: hello
data:
  GREETING: "hello from the otherside"
  index.html: |
    <html>
      Goodbye from this side!
    </html>